/** Faralin light theme for auth components (modals, sign-in/up, user menu). */
export const authAppearance = {
  variables: {
    colorPrimary: '#c5a059',
    colorPrimaryForeground: '#ffffff',
    colorForeground: '#002147',
    colorMutedForeground: '#5c6b7a',
    colorBackground: '#ffffff',
    colorInput: '#ffffff',
    colorInputForeground: '#002147',
    colorBorder: '#d1d5db',
    colorMuted: '#f4f6f8',
    colorRing: '#c5a059',
    colorDanger: '#9b1c2e',
    colorModalBackdrop: 'rgba(0, 33, 71, 0.45)',
    colorText: '#002147',
    colorTextSecondary: '#5c6b7a',
    colorNeutral: '#f4f6f8',
    colorShimmer: '#e8ecf0',
    borderRadius: '4px',
    fontFamily: 'var(--font-sans), Roboto, system-ui, sans-serif',
    fontSize: '0.9375rem',
  },
  layout: {
    socialButtonsPlacement: 'top' as const,
    socialButtonsVariant: 'blockButton' as const,
    shimmer: false,
  },
  elements: {
    rootBox: { width: '100%' },
    main: { backgroundColor: '#ffffff', color: '#002147' },
    cardBox: { backgroundColor: '#ffffff', color: '#002147', borderRadius: '4px' },
    card: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
      borderRadius: '4px',
      boxShadow: '0 8px 24px rgba(0, 33, 71, 0.1)',
    },
    modalContent: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
      borderRadius: '4px',
      boxShadow: '0 12px 32px rgba(0, 33, 71, 0.14)',
    },
    modalCloseButton: { color: '#5c6b7a' },
    headerTitle: {
      color: '#002147',
      fontFamily: 'var(--font-serif), Raleway, system-ui, sans-serif',
      fontWeight: '400',
    },
    headerSubtitle: { color: '#5c6b7a' },
    formHeaderTitle: {
      color: '#002147',
      fontFamily: 'var(--font-serif), Raleway, system-ui, sans-serif',
    },
    formHeaderSubtitle: { color: '#5c6b7a' },
    formFieldLabel: { color: '#002147', fontWeight: '500' },
    formFieldInput: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
    },
    formFieldInput__input: {
      backgroundColor: '#ffffff',
      color: '#002147',
    },
    formFieldInputShowPasswordButton: { color: '#5c6b7a' },
    formButtonPrimary: {
      backgroundColor: '#c5a059',
      color: '#ffffff',
      fontSize: '0.875rem',
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: '0.05em',
    },
    formButtonReset: { color: '#5c6b7a' },
    socialButtonsBlockButton: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
    },
    socialButtonsBlockButtonText: { color: '#002147', fontWeight: '500' },
    alternativeMethodsBlockButton: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
    },
    dividerLine: { backgroundColor: '#d1d5db' },
    dividerText: { color: '#5c6b7a' },
    footerPages: { display: 'none' },
    footerPagesLink: { display: 'none' },
    lastAuthenticationStrategyBadge: { display: 'none' },
    badge: { display: 'none' },
    devBar: { display: 'none' },
    footerActionLink: { color: '#c5a059', fontWeight: '500' },
    footerActionText: { color: '#5c6b7a' },
    backLink: { color: '#c5a059' },
    identityPreviewText: { color: '#002147' },
    identityPreviewEditButton: { color: '#c5a059' },
    formResendCodeLink: { color: '#c5a059' },
    navbar: { backgroundColor: '#ffffff', borderBottom: '1px solid #d1d5db' },
    navbarButton: { color: '#002147' },
    userButtonPopoverCard: {
      backgroundColor: '#ffffff',
      border: '1px solid #d1d5db',
      boxShadow: '0 8px 24px rgba(0, 33, 71, 0.12)',
    },
    userButtonPopoverActionButton: { color: '#002147' },
    userButtonPopoverActionButtonText: { color: '#002147' },
    userButtonPopoverFooter: { display: 'none' },
    userPreviewMainIdentifier: { color: '#002147' },
    userPreviewSecondaryIdentifier: { color: '#5c6b7a' },
    alertText: { color: '#002147' },
    otpCodeFieldInput: {
      backgroundColor: '#ffffff',
      color: '#002147',
      border: '1px solid #d1d5db',
    },
  },
} as const;

/** Sign-up appearance — hides first/last name (collected in onboarding). */
export const authSignUpAppearance = {
  ...authAppearance,
  layout: {
    ...authAppearance.layout,
    showOptionalFields: false,
  },
  options: {
    showOptionalFields: false,
  },
  elements: {
    ...authAppearance.elements,
    formField__firstName: { display: 'none' },
    formField__lastName: { display: 'none' },
    formFieldRow__firstName: { display: 'none' },
    formFieldRow__lastName: { display: 'none' },
  },
};

/** @deprecated Use authAppearance */
export const clerkAppearance = authAppearance;
